### ISSUE TITLE
functions in components not highlighted correctly. 

### ISSUE THREAD

**Issue by jbhatab** [babel/babel-sublime#104]
In the picture you can see render and componentWillMount are just plain white, when they should be green. Also should json objects be yellow/yellow like they are? Looks kinda weird. 

![screen shot 2015-04-20 at 2 38 29 pm 2](https://cloud.githubusercontent.com/assets/2458718/7238937/b2a03552-e76b-11e4-801d-a416a63c6ce4.png)

**Comment by zertosh** [comment]
@jbhatab 

w.r.t. the white class methods, that's because you're using the stock Monokai theme - which doesn't understand short method definitions. babel-sublime comes with "Monokai Phoenix", which has very similar colors to the stock Monokai, but recognizes ES6. (https://github.com/babel/babel-sublime/issues/97#issuecomment-93459132 goes into the difference between a syntax definition and a color theme - it's good to know the difference for these colors issues).

w.r.t. the yellow/yellow. That's a color theme issue. The reason you were seeing them white before babel-sublime is because the stock Javascript syntax definition didn't understand object keys, so they got the default color. babel-sublime does understand object keys, and it so happens that so does the stock Monokai, which is why they're yellow. I won't comment on theme color decisions, but there are lots to choose from that work well with babel-sublime. (from the same thread as ref'd above, https://github.com/babel/babel-sublime/issues/97#issuecomment-93489338 goes a bit more into this).

**Comment by jbhatab** [comment]
pow awesome pow. Monokai Phoenix for the win. Thanks!!
