### ISSUE TITLE
Cpu 100% when using "Javascript (Babel)" syntax highlighting

### ISSUE THREAD

**Issue by lax4mike** [babel/babel-sublime#108]
I started using es6, so I installed babel-sublime for the syntax highlighting.  When I apply the "Javascript (Babel)" syntax highlighter, my cpu spikes.  I found this article, which might explain why:

http://www.sublimetext.com/blog/articles/file-indexing

I do have a lot of files that need to be indexed (inside node_modules), but I'm wondering if there is something that can be optimized with babel-sublime for this task.  Indexing this many files isn't an issue using the regular Javascript syntax highlighter.

**Comment by zertosh** [comment]
As I understand indexing, you only "pay" the cost of indexing when sublime sees a new file, then it's cached. To sublime, all your files are "new" since a new syntax definition (babel-sublime) got added. But I expect that once the re-indexing is done, it'll only then index truly new files - so you should only see prolonged high CPU use once. Does it the CPU at 100% never stop?

**Comment by lax4mike** [comment]
It does stop eventually, and what you said sounds reasonable.  I'll keep an eye on it and see if this is a recurring problem.
