### ISSUE TITLE
speed up babel-transform

### ISSUE THREAD

**Issue by jevzee** [babel/babel-sublime#131]
references #129:

> FYI: I'm still trying to figure out how to make the startup faster. Right now, it starts up a new node process every time you run "Babel Transform". I'd like to keep an instance around for a few min to reduce the load times, but my python is pretty bad :(

Original commit: ["Babel Transform" command](https://github.com/babel/babel-sublime/pull/126)

**Comment by jevzee** [comment]
Cool, that's a great idea about speeding up `babel-transform`. What do you think about spawning a background node server on the first call of `babel-transform`? This server will babelify all incoming requests? It could have a limited lifetime. Consequent `babel-transform` calls will use the background server if it exists or spawn a new one if it isn't available.

**Comment by zertosh** [comment]
I was thinking about the server approach, but I don't want to trigger any firewall warnings or look suspicious if someone is looking at the network activity. Though maybe this option could be enabled via a flag? 

I was hoping that you'd spin up the process, pipe in a JSON encoded string like `{ "source": "", "opts": { ... }` that's new-line terminated, and you'd get back another JSON stream that's new-line terminated. But the process lives on. You know your response is complete because of the new lines. The problem becomes keeping track of concurrent streams. 

I've also considered preemptively keeping a process ready and waiting. But I wonder how that will perform.

I'm open to trying anything out - so if you can build something and works well, then we can give it a go :smile:

**Comment by jevzee** [comment]
I'll give it a try

**Comment by zertosh** [comment]
After thinking about this some more, I realized that holding onto the node instance that's running babel is a bad idea. When you run the plugin, it uses the babel version that is reachable by the file you're transforming. I find this useful when you have several projects on different versions of babel and need to see exactly what babel will output. If you start trying to account for that in some sort of process cache, you're in for trouble. For example, there's no way to know if the babel version changed (e.g. by running `npm update`)

So I'm going to call it quits on this one. Sorry.
