### ISSUE TITLE
class methods not properly syntax highlighted when method arguments span > 1 line

### ISSUE THREAD

**Issue by montemishkin** [babel/babel-sublime#136]
Here is some code to reproduce the issue:

```javascript
class MyClass {
    // syntax is properly highlighted
    my_method(argument1, argument2) {
        // ...
    }


    // syntax is not properly highlighted
    my_method_with_many_arguments(argument1, argument2, argument3, argument4,
                                  argument5, argument6, argument7 ) {
        // ...
    }
}

```

Here is an image showing the issue in action:

![screen shot 2015-06-22 at 12 14 56 pm](https://cloud.githubusercontent.com/assets/12076775/8290505/5cf49df2-18d8-11e5-9daf-3be5e3371a72.png)

I am using Sublime Text 2 (Version 2.0.2, Build 2221).

**Comment by zertosh** [comment]
Unfortunately that's a known limitation of SL - you have to have the entire method on the same line. I'm working on version (https://github.com/babel/babel-sublime/pull/135) that hopefully fixes this and other issues, but it'll only work in the latest SL3 dev build. If you use SL3 dev, then it'll automatically use the new syntax definition. As of right now, the new syntax has feature parity is the old one (bugs and all), but that'll soon change as I make improvements.

**Comment by mathieumg** [comment]
> As of right now, the new syntax has feature parity is the old one (bugs and all), but that'll soon change as I make improvements.

I was wondering, I saw the PR pass by this weekend and the 7.0 release this morning, today I updated the package in my ST3 dev build wondering if something was supposed to have changed! Good to know, thanks for updating this, I'll keep following closely. :+1:

**Comment by zertosh** [comment]
I bumped it to 7.0 because SL3 automatically uses the new syntax if it's available. So everyone that's on SL3 is using the new syntax right now without even knowing it hehe. The feature parity thing is a bit of a -lie. The new syntax is actually much faster - when parsing large files things run smoothly, and it also supports comments in places that weren't getting matched before (I won't say where :stuck_out_tongue:) https://github.com/babel/babel-sublime/commit/a351f3b1b1b2c7209845ce66cb752e8dd7155489
