### ISSUE TITLE
text nodes in jsx are highlighted like js

### ISSUE THREAD

**Issue by AprilArcus** [babel/babel-sublime#14]
![screenshot 2015-01-21 13 56 05](https://cloud.githubusercontent.com/assets/2045543/5845999/4b6c8958-a175-11e4-9563-fb1c47c94c6a.png)

Using the included Monokai Phoenix scheme. This lints (in [jsxhint](https://github.com/STRML/JSXHint) + [SublimeLinter-jsxhint](https://github.com/SublimeLinter/SublimeLinter-jsxhint)) and transpiles correctly.

**Comment by Dashed** [comment]
It seems unusual to be hardcoding text that like that in a react component; especially when it's desirable for the component to be reusable.

```js
React.createClass({
    render: function() {

        // fetch a sonnet from somewhere (ajax, flux store, etc)
        let sonnet = 'two households ...';

        return (<p>{ sonnet }</p>);
    }
});
```

**Comment by Dashed** [comment]
But you're absolutely right that keywords + quotes/semicolons shouldn't be scoped between JSX tags when it's not between `{ }`.

**Comment by zertosh** [comment]
This is a though one. What's funny is that I _knew_ about it, but always brushed it off because I wrap all my text in `{ }`. @Dashed, what do you think the behavior should be? Everything between a tag that is not in `{ }` should be matched as a string?

**Comment by Dashed** [comment]
@zertosh Glancing at the grammer, http://facebook.github.io/jsx/, looks like `JSXText` (or sequence of `JSXTextCharacter`). Unsure if provided scope for this. I still don't know tmLanguage :sweat_smile:.

**Comment by cwmanning** [comment]
+1

**Comment by chrisjhoughton** [comment]
+1

**Comment by zertosh** [comment]
Unfortunately, Sublime doesn't support multiline matches, which make it impossible to match the text inside of tags. Sublime's new [syntax](http://www.sublimetext.com/docs/3/syntax.html) shows promise, but it came out just a few weeks ago - it needs a bit of time to mature and I need to think about how to work it into babel-sublime.

FWIW, you can always wrap your text like so `{"text"}`.

**Comment by chrisjhoughton** [comment]
Yeah thanks I'll do that from now on, just frustrating the finished working components that were working great with sublime-react now look like this: (and there's no way of switching back)

![screen shot 2015-04-17 at 14 09 55](https://cloud.githubusercontent.com/assets/2671525/7202563/8713cd70-e50b-11e4-89d5-129313864038.png)

**Comment by zertosh** [comment]
@chrisjhoughton sublime-react didn't actually work great. The text inside JSX tags was matched as regular JS, so keywords like "for" and "if" got syntax highlighting. However, I ran a quick test and you're partly right. It turns out that if the quote is in between two characters, it doesn't match as a "string" - but if it's preceded or followed by a space, then it is:

![1-2-3-4](https://cloud.githubusercontent.com/assets/830952/7204031/27450ca6-e4ed-11e4-9b56-4d8740a017fb.png)

That behavior is not just limited to JSX, it does it everywhere - which IMHO, is incorrect:

![5](https://cloud.githubusercontent.com/assets/830952/7204065/62575bbe-e4ed-11e4-95c4-6de8477bdf86.png)

But this has given me an idea. Since it's only non-self-closing components that can have contents, I don't have to match the entire tag, just the `>` and the `</`. Since `</` is syntactically invalid JS, it's pretty safe to match and not grab any false positives. I have see if then excluding `{`/`}` is problematic.

---

If wrapping your strings in `{' '}` is a deal breaker, you can always just manually install the last sublime-react tmLanguage in your `Packages/User`:


```sh
curl "https://raw.githubusercontent.com/reactjs/sublime-react/ec17f5d/syntax/jsx/tmLanguage/JavaScript%20(JSX).tmLanguage" -O
```

**Comment by zertosh** [comment]
You can follow the progress in https://github.com/babel/babel-sublime/pull/102. Feel free to test it. It's a pretty big change, so I'm going to personally use it this coming week before rolling it out.

**Comment by tobia** [comment]
I tried this package, but I'm uninstalling in favor of the original [syntax file from the ReactJS package](https://github.com/reactjs/sublime-react/tree/ec17f5dfd00eaa326dc299a4febd46cac21e7904/syntax/jsx/tmLanguage), before it was <s> deprecated </s> removed without warning.

This syntax file is too colored. Everything is blue, not just static text inside tags, as per this current issue, but all variable names too!

Here is some random file with the ReactJS syntax. It's nicely balanced, it highlights important keywords, such as **this, var, function, return,** HTML tags, and object keys, while leaving the bulk of the code, such as variable names and static text, in black:

![reactjs](https://cloud.githubusercontent.com/assets/48756/7302075/185f8276-e9e7-11e4-9fbc-d51bd835a1ad.png)

And this is the Babel syntax:

![babel](https://cloud.githubusercontent.com/assets/48756/7302087/3061625e-e9e7-11e4-894c-13df64edaabc.png)

***Yo Dawg, I heard you like blue, so I put more blue in you blue!!***

**Comment by zertosh** [comment]
@tobia Thinking of themes and syntax definitions as the same thing is a common misconception. Things are blue because your theme decided so - not the syntax definition. https://github.com/babel/babel-sublime/issues/104#issuecomment-94554891 goes into this in more detail.

**Comment by tobia** [comment]
Nope. Only your syntax file colors everything in blue. All other syntax file, including the stock Javascript and the ReactJS one, only color in blue some keywords, such as **function, var, this,** and HTML tags, as you can see from the first screenshot.

I'm aware that there's a level of indirection between syntax file and color scheme: the syntax tags, or whatever they are called, such as `string.quoted.double.js`, so it's possible for syntax authors to blame color scheme authors and vice versa.

But this is a standard color scheme (Solarized Light, installed with ST2) and only your syntax file causes this problem, out of the hundred or so syntax files in my installation. So it's pretty much a bug that goes here.

**Comment by zertosh** [comment]
@AprilArcus @Dashed: I merged https://github.com/babel/babel-sublime/pull/102 and published it was v6.0.0. I'm leaving what the [spec](https://facebook.github.io/jsx/) calls "JSXText" unscoped in the syntax.   The main reason is so that themes give it their chosen default color and not a string-like color - since it'll be confusing for those (like me) that already wrap children strings in JSX with `{'…'}`.

---

@tobia I think we have a misunderstanding. I thought I understood what you meant, but I don't. Can you open a new issue? Please post some screenshots and sample code (that I can copy paste), with a bit more detail. If you stand over a piece of code in Sublime and press "shift+control+P", it'll show you what the scope is at the given point in the status bar. Use that info to describe your issue with the results from babel-sublime and sublime-react.

**Comment by AprilArcus** [comment]
Thanks, @zertosh, this looks great to me!

**Comment by chrisjhoughton** [comment]
Amazing, thanks so much
