### ISSUE TITLE
Function and method names no longer highlighted

### ISSUE THREAD

**Issue by simonsmith** [babel/babel-sublime#144]
I've updated to the latest version and seem to have lost function and method name highlighting:

Dev:
<img width="569" alt="screen shot 2015-07-13 at 09 32 47" src="https://cloud.githubusercontent.com/assets/360703/8645759/1677eeb8-2942-11e5-8170-77bf67971c4c.png">

Beta:

<img width="566" alt="screen shot 2015-07-13 at 09 57 30" src="https://cloud.githubusercontent.com/assets/360703/8646180/7f9895ac-2945-11e5-9b58-56231695e809.png">

Any idea how I can manually fix this?

Thanks

**Comment by simonsmith** [comment]
Reinstalling the theme seemed to fix it

**Comment by simonsmith** [comment]
Sorry, seems the issue is there in the dev builds of Sublime. Fine if I use the beta. If anyone else can replicate that would be great

**Comment by simonvizzini** [comment]
The highlighting of function and method calls was actually reported as a bug at sublimehq: https://github.com/sublimehq/Packages/issues/63

This is the sublime fix for this issue: https://github.com/sublimehq/Packages/commit/2a81219d66df8af4ec7b2d6a56ec4a0a3bf93aff

And it seems Babel has adapted this fix: https://github.com/babel/babel-sublime/commit/9ee07f2eaf262b88f3534587cbe0de9f2596a67c

So apparently the correct behavior is to not highlight functions and method names, but I actually prefer having them highlighted! Now I have way too many white lines in my code which looks and reads kinda awkward. I found the highlighting really useful for skimming through code because it made spotting method calls very easy. I don't like this new "correct" behavior at all.

**Comment by simonsmith** [comment]
Interesting. I guess this can be added back manually into whatever `.tmTheme` we happen to use?

**Comment by simonvizzini** [comment]
Yes I think so. From what I understand Sublime has adapted the Babel syntax file as a default for JS files. So one solution would be to fork the syntax file and revert the changes. But that's something I'd like to avoid...

**Comment by simonvizzini** [comment]
By the way, this comparison screenshot is not correct anymore with the recent changes: https://raw.githubusercontent.com/babel/babel-sublime/45c7d37/screenshots/compare-react-class@2x.png

Inside the 'submit' function, the methods 'post', 'send' and 'end' of the 'request' object as well as 'this.setState' are not highlighted anymore, they now look like on the right screenshot.

So I wonder if it was really intentional to remove this syntax highlighting on method calls? It makes it more readable in my opinion.

**Comment by zertosh** [comment]
Yup, the rationale in https://github.com/sublimehq/Packages/issues/63 made sense so I decided to rename the scopes. I personally like my function calls to have a color, but I don't think any theme colors them. However, that's an easy tweak you can make. For example, this is my personal theme and relevant [change](https://github.com/zertosh/dracula-theme/commit/6dc31f9a40d9b8327dec046f5fa2d060094d0639#diff-3f6c9bc17eb7b0c1db08903fe544741fR192).

> So I wonder if it was really intentional to remove this syntax highlighting on method calls? It makes it more readable in my opinion.

@simonvizzini It's important to understand the difference between a syntax definition and a theme. babel-sublime is a syntax definition. I go into more detail in https://github.com/babel/babel-sublime/issues/97. But basically, it's not that babel-sublime decides to color something or not. It's that it decided to not call something an "entity.name" but a "variable" instead, and your theme don't color variables. But, it's easy to tweak themes :smile:

**Comment by zertosh** [comment]
> By the way, this comparison screenshot is not correct anymore with the recent changes:

Yeah, I won't be fixing those until I'm done with flow support. It takes forever to make perfect screenshots.

**Comment by simonvizzini** [comment]
Ah, I see! I obviously have no clue about syntax files and themes :-) So thanks for the clarification!

What about the "Monokai Phoenix" color scheme that ships with Babel? Any plans to change it so it will highlight function calls again with the recent syntax file changes? In the meantime I will try to tweak the color scheme myself, doesn't look too hard.

**Comment by zertosh** [comment]
@simonvizzini No problem. I'm actually planning on deprecating "Monokai Phoenix" - it's in the latest [announcement](https://github.com/babel/babel-sublime/blob/master/messages/7.1.0.txt). I've made some changes like https://github.com/babel/babel-sublime/commit/7f0b796ff4d281de892a3e9e39581a30e93d53a0 so that the stock Monokai looks more like Monokai Phoenix.

Once flow support is fully done, I'll add finer color control to my personal theme for that ([dracula/dark fork](https://github.com/zertosh/dracula-theme/tree/dark)), and publish it so it serves as a basis for whoever wants to implement that level of control over the type color. I won't bundle it with babel-sublime because the colors are, hmmm, not for everyones taste:

![dracula-es7](https://cloud.githubusercontent.com/assets/830952/8652290/e2db660c-294b-11e5-9927-7b3ababb6908.png)

**Comment by dozoisch** [comment]
@zertosh oh that theme looks good!

**Comment by simonsmith** [comment]
So just to clarify, if I want to bring method highlighting back to the dev version of Sublime I need to make some updates to the theme I am currently using. Any tips on what part I would need to edit?

I'm currently using Afterglow Monokai

Thanks

**Comment by zertosh** [comment]
@simonsmith You'd need a scope like [this](https://github.com/zertosh/dracula-theme/blob/6dc31f9a40d9b8327dec046f5fa2d060094d0639/Dracula.tmTheme#L411-L423)
