### ISSUE TITLE
Multiline ternary expression syntax highlighting vars as object properties

### ISSUE THREAD

**Issue by robmclarty** [babel/babel-sublime#151]
When writing a ternary expression across multiple lines, the first operand, written in this notation, is highlighted as if it were a property of an object literal which is every so slightly misleading when glancing at such code.

Example:

```javascript
function things() {
  var thing, otherThing;

  return thing !== null ?
    thing :
    otherThing;
}
```

It looks like the highlighter thinks this snippet is an object literal like this:

```javascript
{
  thing : 
  otherThing
}
```

It could be argued that it's clearer to write the multi-line ternary with each line *beginning* with "?" or ":", which highlights properly:

```javascript
function things() {
  var thing, otherThing;

  return thing !== null
    ? thing
    : otherThing;
}
```

However, I believe the first example's notation is *also* a valid way to express the ternary over multiple lines, and could be argued to be clearer than the second example because the "?" and ":" are at the end of the lines and help indicate to a reader that "there's more stuff going on here on the next line".

The point is, some people like writing it one way, and others, the other way, and both are valid.  However the first example doesn't get highlighted as expected and seems like a bug in the highlighter.

**Comment by zertosh** [comment]
This is a known issue that I'm hoping will go away with the rewrite I'm doing to support flow types. The bug you're seeing is because it's really hard to differentiate between an object property, a label, a switch case, and a ternary. These all have a `:` and you have to somehow match those cases with regex – not an easy task. Sublime recently introduced a new way to define syntax definitions that will help with telling the different `:` apart. So stay tuned.

**Comment by robmclarty** [comment]
Cool. Thanks for reply :)
