### ISSUE TITLE
Variable in a backtick string is not highlighted

### ISSUE THREAD

**Issue by gajus** [babel/babel-sublime#169]
<img width="472" alt="screen shot 2015-08-28 at 10 31 53" src="https://cloud.githubusercontent.com/assets/973543/9543320/065927c0-4d70-11e5-8501-8eb5a0240377.png">

Is there a way to make the variable stand out more? e.g. `action.name` could be white.

**Comment by zertosh** [comment]
Actually I just fixed that last night in #168. Can you make sure that you're using babel-sublime v8.0.5 and ST3 build 3095?

**Comment by zertosh** [comment]
And I just made another change so that stock themes color the `${` and `}` (see #170)

**Comment by gajus** [comment]
I am using v8.0.5, though my ST build it 3083. Where are you getting the 3095 build from?

**Comment by gajus** [comment]
I see it. http://www.sublimetext.com/3dev Yes, I can confirm that once updated to 3095 syntax highlighting does work.

**Comment by zertosh** [comment]
Cool. For some background on why this is the case, check out the [7.1.0 release notes](https://github.com/babel/babel-sublime/blob/771aca71887fea5a43385505f5346cfb29c7c97e/messages/7.1.0.txt).

**Comment by gajus** [comment]
Upgrading to the 3095 brakes syntax highlighting:

<img width="961" alt="screen shot 2015-08-29 at 11 36 03" src="https://cloud.githubusercontent.com/assets/973543/9561555/2782ae58-4e42-11e5-8182-a476373ddd62.png">

**Comment by zertosh** [comment]
That's a ST3 bug. It's using the stock JavaScript syntax to highlight the js block, and it thinks that the `</div>` is the start of a regex. The way I've dealt with it, is by turning off the stock JavaScript syntax, so that ST3 then uses babel-sublime. Unfortunately, there is no way to give priority to the different syntaxes used in embeds. For instructions, see [Advanced Usage](https://github.com/babel/babel-sublime#advanced-usage).
