### ISSUE TITLE
Breaking change in recent update

### ISSUE THREAD

**Issue by Prinzhorn** [babel/babel-sublime#200]
Hey, I've just fired up Sublime and some of my files don't render correctly anymore. I created a simple demo case. The obvious problem is the = inside the string. But also why are `a` and `b` orange? Throughout my files many variables are now orange, others are still white. It doesn't look like there's a logic behind it.

![screenshot from 2015-10-20 09 44 04](https://cloud.githubusercontent.com/assets/679144/10601135/bcf2a5a6-770f-11e5-9cf0-c35d0a0d4b65.png)

```js
if(a) {
	c();
}

if(a()) {
	c();
}

if(a('b')) {
	c();
}

if(a('b=') > -1) {
	c();
}
```

**Comment by zertosh** [comment]
That was fixed in v8.6.1

**Comment by Prinzhorn** [comment]
@zertosh awesome, just upgraded. Is there a changelog in this repo? I was looking for one before opening an issue. I also couldn't find a history on https://packagecontrol.io/packages/Babel either

**Comment by zertosh** [comment]
sigh, I _should_ keep a changelog, but I don't :disappointed: The commit messages are usually pretty good though. You can compare between tags to see what changed between versions: https://github.com/babel/babel-sublime/compare/v8.6.0...v8.6.1

I've been making a lot of changes in the last 3 weeks as I port over the rewrite from #183 into master. I'm doing it in small parts because there are actually 2 different syntaxes for different versions of Sublime. One is way more flexible than the other, but not all users have versions of Sublime that support it. So I'm trying to keep as much parity between the two until I've reached the technical limits of the old syntax – I then plan on deprecating it and only focusing on the new one.

**Comment by Prinzhorn** [comment]
Don't worry, I didn't thought about looking at the tags. Keep up the good work!
