### ISSUE TITLE
Plain text inside jsx tags has meta.tag.jsx scope

### ISSUE THREAD

**Issue by voronianski** [babel/babel-sublime#204]
In latest update content of jsx tags has the same scope as tags, it was different in previous version, see example:

![](https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-10-22%20%D0%B2%2014.02.06.png)

**Comment by zertosh** [comment]
So the reason I scoped tags themselves as `meta.tag.jsx` is so that Sublime will underline the beginning and end tags if your cursor is on top of them (who knew that's how that worked?!?!?!) :

![oepqe](https://cloud.githubusercontent.com/assets/830952/10669750/02435000-7897-11e5-9a25-c2376e2694bb.png)

I didn't think much of the content scope though. Does #206 work for you?
