### ISSUE TITLE
Package is unsearchable in Package Control

### ISSUE THREAD

**Issue by deoxxa** [babel/babel-sublime#28]
Neither "es6" nor "jsx" returns a result in Package Control's search interface for 6to5. This isn't necessarily a bug, but maybe it's something to think about.

![screen shot 2015-02-11 at 1 49 48 pm](https://cloud.githubusercontent.com/assets/479055/6141095/f49fb056-b1f4-11e4-9f99-669f7f67c934.png)
![screen shot 2015-02-11 at 1 50 04 pm](https://cloud.githubusercontent.com/assets/479055/6141097/f4a11e78-b1f4-11e4-9327-f5a22f1f3c77.png)
![screen shot 2015-02-11 at 1 50 20 pm](https://cloud.githubusercontent.com/assets/479055/6141096/f4a07392-b1f4-11e4-9903-4ed8e0aed472.png)

**Comment by grapegravity** [comment]
:+1:, it took me complaining and a coworker telling me this existed for me to find it. :stuck_out_tongue_winking_eye:

**Comment by Dashed** [comment]
IMO, 6to5-sublime's mission should be to support any syntax that 6to5 support. That's why it's forked from https://github.com/Benvie/JavaScriptNext.tmLanguage 

6to5-sublime is pretty young, as it only supports ES6 and JSX (latter being baked in recently). 

ES6 and JSX aren't 'exclusive' to 6to5, as it also support other useful transforms. See: https://github.com/6to5/6to5/issues/568

Thus, you shouldn't be thinking of using 6to5-sublime just for its ES6 + JSX syntax highlighting, but for highlighting "6to5 code". 

Also, 6to5 may be renamed to something else soon.

-----

It seems the fuzzy search is applied only on the title, and doesn't include the description.

**Comment by deoxxa** [comment]
Oh I totally agree there. 6to5 isn't a one (or two?) trick pony. I'm just thinking of people who potentially don't know about 6to5 and just want to highlight their JSX code or something, who will search for "JSX". It'd be cool if this could be another entry point to the 6to5 universe! On top of that, it actually does a better job at highlighting JSX code than anything that *does* come up if you search for "JSX".

**Comment by Dashed** [comment]
Do people really shop for sublime plugins through the command palette?

I'd imagine folks would do some preliminary research on the plugins they're looking to install: 

1. Search what they want: 
   
   https://packagecontrol.io/search/jsx
   https://packagecontrol.io/search/es6

2. Browse GitHub repo.
3. Install through command palette using partial (or full) name of the plugin in question.

If anything, this sounds like a human factor issue on Package Control's end.

Due to the nature of searching for Sublime plugins command palette, this seems to imply that the package should be renamed; which is probably unlikely to happen.

**Comment by deoxxa** [comment]
I know that I do that to look for packages - perhaps I'm in the minority there though. Anyway, if there's nothing that can be done, then there's nothing that can be done. I just didn't want anyone to miss out on this package who might benefit from it. If it turns out that most people search for packages in another way, this isn't even a problem.

**Comment by Dashed** [comment]
AFAIK, there doesn't seem to be a way to add keywords: https://github.com/wbond/package_control_channel/tree/master/repository

>  I just didn't want anyone to miss out on this package who might benefit from it.

I share this sentiment as well :smile: 

I think @zertosh was supposed to make an official 6to5 blog post on this. It's understandable that he's probably busy to get around to it.

**Comment by zertosh** [comment]
@deoxxa The command palette fuzzy search only matches the title and not the description - this kinda sucks actually. But we are on the _front page_ by default hahaha :smile_cat: 

![rwtke](https://cloud.githubusercontent.com/assets/830952/6141765/3bec370e-b178-11e4-819f-5096159e03e3.jpg)

And I owe @Dashed a blog post on 6to5-sublime, and my manager a blog post on React/Flux - sigh. Blog post debt is the worst heh. I'll make the time for it this week.

**Comment by Dashed** [comment]
@zertosh Hah. No worries. I know you'll come around on that blog post.

Next thing you know, is that you'll try convince your manage to use FB Relay instead of Flux :stuck_out_tongue:

**Comment by zertosh** [comment]
@deoxxa The package has been renamed to babel - not that it helps with searching by "js" but at least there is a link in the front page of http://babeljs.io/

![xldtw](https://cloud.githubusercontent.com/assets/830952/6205097/3469caee-b530-11e4-9a90-8c46381d03ef.png)

**Comment by robert-chiniquy** [comment]
I can't find babel-sublime in `Package Control: Install Package` :'/

**Comment by zertosh** [comment]
@robert-chiniquy It seems that there's a chunk of packages missing - i'd wait a bit to see if the issue clears up

**Comment by robert-chiniquy** [comment]
Thanks for the heads up

**Comment by vferko** [comment]
The Babel still can't be installed through Package Control. Any news or a workaround?

**Comment by zertosh** [comment]
@vferko The latest issue mentioned with package control was promptly fixed https://github.com/wbond/package_control/issues/955. If you're still having problems, please open a new issue.
