### ISSUE TITLE
Syntax highlight with objects is broken

### ISSUE THREAD

**Issue by caub** [babel/babel-sublime#305]
![image](https://cloud.githubusercontent.com/assets/3134574/22686735/929cc8f8-ed25-11e6-9d70-0874dedfd4a6.png)

Or is it just the color theme that put object keys and string litterals in same color?
```
function _fetchJSON(url, method='GET', body) {
    return fetch(exports.backendURL+'/'+url, {
        method, 
        mode:'cors', credentials: 'include',
        //...
    });
}
```

**Comment by geordiemhall** [comment]
+1 

Was also looking for a solution to this – not sure if the issue as with the colour scheme or the syntax

**Comment by caesarsol** [comment]
That scope is `string.unquoted`, your theme (Monokai I guess) has defined the color on the `string` scope.

If you define something like `string.quoted, string.interpolated, keyword.other.template` you'll get it right, try with a different color scheme!

**Comment by geordiemhall** [comment]
Oh thanks! Created a new definition for `string.unquoted` in my custom Monokai and worked like a charm

**Comment by A-312** [comment]
> Oh thanks! Created a new definition for `string.unquoted` in my custom Monokai and worked like a charm

Can you explain about how to do that ?

**Comment by geordiemhall** [comment]
@A-312 I haven't used Sublime in years, so there might be a better way than this, but I just tested this (kind of annoying) workflow:
* Go to `%appdata%\Sublime Text 3\Installed Packages` and you should have a `Monokai Extended.sublime-package` file (this is AppData\Roaming)
* Make a copy of this, and change the extension from `sublime-package` to `.zip`
* Extract that zip (sublime packages, like nuget packages, are just zip files)
* You should find a bunch of .tmTheme files and some other stuff
* Open the tmTheme that isn't working (in my testing just now `Monokai Extended Bright` didn't work properly for unquoted strings, but the base `Monokai Extended` one did)
* I opened the `Monokai Extended.tmTheme` in a text editor, and copied the whole `<dict>` block it used for `string.unquoted`, then pasted it in to the `Bright` one
* Once you're done editing, select all of the files that were unzipped, and zip them back up (they must be at the root of the zip, so careful not to zip up their containing folder)
* Close Sublime if you had it open, since not sure how it handles changing packages out from under it
* Move that newly created zip into the `Installed Packages` directory
* Rename the original `Monokai Extended.sublime-package`'s extension to something else so Sublime won't try to load it, eg. `Monokai Extended.sublime-package.backup`
* Rename the new `.zip` you made to `Monokai Extended.sublime-package`
* Open Sublime back up and the Monokai Bright theme should now show the unquoted string keys in white instead of yellow when used with Javascript (Babel) syntax

![image](https://user-images.githubusercontent.com/3511383/81880289-7fea0200-95d0-11ea-8236-c55b08b6ddc4.png)

To save you the hassle if all you wanted was the Bright theme, here's the zip version of the `.sublime-package` I just made (though no guarantees I did the most robust job etc.) so you can chuck it in and rename.

[Monokai Extended.zip](https://github.com/babel/babel-sublime/files/4625418/Monokai.Extended.zip)
