### ISSUE TITLE
Feature Request: Different color on Component jsx

### ISSUE THREAD

**Issue by Quanthir** [babel/babel-sublime#307]
Hello,

In atom, the component jsx tags show with different color. But unfortunately this is not the case for Sublime Text.

It will be awesome if a tag starts with uppercase, add it to class scope so that Color schemes shows it in different color.

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi it scope components differently, but you still need to check your color scheme.

**Comment by Thom1729** [comment]
I like this idea a lot, and I've opened an issue on the core Packages tracker.

Future versions of babel-sublime will be effectively downstream from the core JavaScript package, so that's probably the best place to address this request. If there's no consensus for adding it to the core package, then I'll probably add it as an optional feature of [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom).
