### ISSUE TITLE
Error of ignored_packages

### ISSUE THREAD

**Issue by MOONLIGHTV** [babel/babel-sublime#314]
My version of ST3 is 3126.
When I added <"ignored_packages": ["JavaScript"],> this option to setting, I got an Error:
![default](https://cloud.githubusercontent.com/assets/14039419/24320497/7d44fa6e-1171-11e7-952b-2c5314794208.png)
 What's wrong with it?

**Comment by borela** [comment]
Try FJSX15 https://github.com/borela/naomi you won't need to disable the core Javascript package

**Comment by Thom1729** [comment]
It's never necessary to disable the core JavaScript syntax when using Babel, and it's probably not a great idea. For the next version, I've removed that recommendation from the readme.

This particular problem wouldn't come up anymore because the core JSON syntax no longer lives in the JavaScript package anyway, so I'm closing this issue.
