### ISSUE TITLE
Inside interpolated string: Tap $ to add ${  } around selection

### ISSUE THREAD

**Issue by jayliu50** [babel/babel-sublime#341]
When I'm in the interpolated string scope (below), it would be super awesome if I could make a selection, and tap $ to put `${` `}` around my selection. 

Scope: 
```
source.js
meta.jsx.js
meta.embedded.expression.jsx
string.interpolated.js
```

**Comment by gorgos** [comment]
And more importantly to able to add the `` around a selection.

**Comment by Thom1729** [comment]
The new v10.0.0-beta.1 release uses the same scopes as the default JavaScript syntax, so the default package's keybinds will automatically work.

At the moment, there is a bug in the default package's keybinds because the template string scopes were changed and the keybinds were not updated accordingly. (My bad.) There is [a PR to fix this](https://github.com/sublimehq/Packages/pull/2255).

I'm closing this issue because the babel-sublime end of the fix is complete (as of the beta) and the Sublime end only awaiting a merge. You can take advantage of the fix right away by installing the babel-sublime beta and adding the fixed keymap from the linked PR to your User directory.
