### ISSUE TITLE
Different colored backticks for template strings depending on presence of interpolation

### ISSUE THREAD

**Issue by switz** [babel/babel-sublime#369]
<img width="650" alt="Screen Shot 2019-05-08 at 1 20 48 AM" src="https://user-images.githubusercontent.com/990166/57353884-89c06600-712f-11e9-96fb-8ff6e90bec17.png">

I currently use single quotation marks for static strings (line 1), but I'm planning to switch to template strings (backticks, line 2 below) everywhere. It seems like backticks are colored red in Monokai, while single quotes are colored yellow.

This got me thinking about how it might be nice if static template strings' backticks were colored yellow similar to single quotes, but red if they have interpolated variables.

Now maybe some people would hate this, and it's quite likely it's not even necessarily possible to theme (I've never written a theme), but I actually think it would be kind of nice and _somewhat_ match current functionality (I understand why one might take the opposing position).

And who knows, maybe it's bad practice to color the same characters differently.

Any insight is appreciated. Thanks for an awesome lib!

**Comment by Thom1729** [comment]
I don't think that this would be desirable as the default behavior, because the scopes for string punctuation are standardized. In addition, determining whether a template string contains an interpolation could be problematic because the current version of Sublime doesn't lookahead across line boundaries.
