### ISSUE TITLE
Turn selection into template literal

### ISSUE THREAD

**Issue by idleberg** [babel/babel-sublime#371]
Sublime Text's default JavaScript syntax package has one very nice feature I miss in this package. A selection within a backtick-enclosed string can be turned into a template literal by pressing <kbd>$</kbd>.

![js](https://user-images.githubusercontent.com/1504938/62026384-2a786c00-b1db-11e9-806c-a6ca59701766.gif)

Other default languages such as Ruby or CoffeeScript also have this feature. It would be amazing if you could add this to the Babel package.

**Comment by Thom1729** [comment]
The new v10.0.0-beta.1 release uses the same scopes as the default JavaScript syntax, so the default package's keybinds will automatically work.

At the moment, there is a bug in the default package's keybinds because the template string scopes were changed and the keybinds were not updated accordingly. (My bad.) There is [a PR to fix this](https://github.com/sublimehq/Packages/pull/2255).

I'm closing this issue because the babel-sublime end of the fix is complete (as of the beta) and the Sublime end only awaiting a merge. You can take advantage of the fix right away by installing the babel-sublime beta and adding the fixed keymap from the linked PR to your User directory.
