### ISSUE TITLE
Isn't highlighting JSX

### ISSUE THREAD

**Issue by Yonier** [babel/babel-sublime#372]
i tried to use differents scheme color, but it doesn't show me the JSX wel highlighted...

Image: [
![image](https://user-images.githubusercontent.com/8054452/62734535-42c86200-b9f7-11e9-82c7-37bd442476fc.png)
](url)

https://i.imgur.com/rSYBUO3.png

I'm using Monokai Gravity V2 color scheme. thanks!

**Comment by zamarawka** [comment]
@Yonier It looks like you use vue.js and this in case template isn't jsx. This is regular vue.js syntax for templates. You also wrap html into [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), so it shouldn't highlighting. If you want to have syntax highlighting use [Single File Components (SFC)](https://vuejs.org/v2/guide/single-file-components.html). This is good solution for vue.js ecosystem and it could easy bootstrap by vue-cli.

**Comment by Yonier** [comment]
> @Yonier It looks like you use vue.js and this in case template isn't jsx. This is regular vue.js syntax for templates. You also wrap html into [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), so it shouldn't highlighting. If you want to have syntax highlighting use [Single File Components (SFC)](https://vuejs.org/v2/guide/single-file-components.html). This is good solution for vue.js ecosystem and it could easy bootstrap by vue-cli.

Thank you for your response!... do you know a way without using SFC? all my VueJS code is in a .JS file

**Comment by zamarawka** [comment]
One possible way you could get highlighting is actually use [jsx for vue](https://vuejs.org/v2/guide/render-function.html#JSX) instead of strings templates. It will optimise performance and bundle size of your app, but it will took a time for refactor code from string templates to render functions. As my opinion, this work will be a same as goes to SFC.

As I get from your image, you use Vue.js as widget for your multipage site. In this case you could define template [direct inside html](https://vuejs.org/v2/guide/#Declarative-Rendering) and write business logic in separate js file, witch bind to template by setting `el` property of your component.

Anyway, this issue doesn't relates to babel-sublime package.

**Comment by Thom1729** [comment]
babel-sublime does not support highlighting of HTML or other syntaxes inside template strings. It's something that could conceivably be added, but I suspect that different users would have different requirements anyway.

The [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom) package does support this in a customizable way via the `custom_templates` option.
