### ISSUE TITLE
JSX Comment Highlighting

### ISSUE THREAD

**Issue by IPWright83** [babel/babel-sublime#381]
I've noticed that comments within JSX are a little odd in that a single line comment renders with un-commented brackets (white) around the edge of the statement. I'm wondering if it would make sense for a single line block with comment to render completely grey as a comment block?

![image](https://user-images.githubusercontent.com/1374775/75557253-948a1580-5a37-11ea-82e8-b4bfa078eac0.png)

**Comment by Thom1729** [comment]
The curly braces are not part of the comments. (I checked the [JSX spec](http://facebook.github.io/jsx/) just to be sure.) Syntactically, the interpolation is empty (because the parser ignores the comment entirely), but that's allowed. So it wouldn't really be correct to scope the curly braces as comments.
