### ISSUE TITLE
Template literal syntax highligting now broken

### ISSUE THREAD

**Issue by pookage** [babel/babel-sublime#398]
Looks like the syntax highlighting for string / template literals has been broken in the latest update:

- `$`, `{` and `}` are now all the same colour as the variable inside
- HTML inside a template literal is now no-longer highlighted at all

![image](https://user-images.githubusercontent.com/3370135/114394536-38c71100-9b93-11eb-9598-deadf2b41e44.png)

![image](https://user-images.githubusercontent.com/3370135/114394686-6449fb80-9b93-11eb-9375-e8f8a3f0266e.png)

**Comment by Thom1729** [comment]
The punctuation is working as intended. The new syntax uses the community-consensus standard scopes for `${}`. If you'd like them to be highlighted differently, you can do so in your color scheme by targeting `punctuation.section.interpolation`. (Likewise, the backticks themselves are deliberately scoped like quotation marks.)

I'm a bit confused about the HTML. As far as I know, Babel has never identified HTML content inside template literals. I just tried it manually with the previous stable release (v8.6.1) and it didn't highlight the HTML in the string, and the old syntax definition doesn't seem to have any support for that. Can you confirm that it was working in your environment pre-update?

If the previous Babel version supported this and I've somehow missed it, then I'll definitely correct that. Otherwise, you might try out [JS Custom](https://github.com/Thom1729/Sublime-JS-Custom). It supports embedding arbitrary languages in template literals via the `custom_templates` option.

**Comment by pookage** [comment]
> I'm a bit confused about the HTML. As far as I know, Babel has never identified HTML content inside template literals.

Ah, strange! I was using this highlighter up to now and it was the default for all my `.js` files for the past few years so I've just grown used to it highlighting HTML correctly.  Perhaps another plugin I had installed aeons ago is what was making Babel behave nicely like this, ah well. Thanks anyhoo - I will give that JS Custom thingie a go 👍
