### ISSUE TITLE
Highlighting for Optional Chaining Operator is broken.

### ISSUE THREAD

**Issue by araneavalon** [babel/babel-sublime#408]
The Optional Chaining Operator `?.` is incorrectly defined as `.?` in the sublime-syntax specification.

This has been fixed in the [Sublime-JS-Custom](https://github.com/Thom1729/Sublime-JS-Custom) repository as of commit https://github.com/Thom1729/Sublime-JS-Custom/commit/1ed59ef8224eacf8768543d3f268a3f7a8e8ce32 but that fix hasn't been propagated to this repository.

**Comment by Thom1729** [comment]
Fixed in the v11 beta. If you're running ST4, you can try the beta by specifying `"install_prereleases": ["Babel"]` in your Package Control settings. The stable release should be out soon.

Unfortunately, the linked commit never ended up in a stable release. (JS Custom v2.4.2 was pulled due to bugs.) It may be possible to backport the fix for ST3 users; I'll look into this.

**Comment by Thom1729** [comment]
Fixed in v11.
