### ISSUE TITLE
Local Variable Highlighting

### ISSUE THREAD

**Issue by aldendaniels** [babel/babel-sublime#49]
**sublime-react:**
![screen shot 2015-02-24 at 2 49 04 pm](https://cloud.githubusercontent.com/assets/4658558/6358882/6e58da0a-bc34-11e4-99ca-14484b25a60e.png)

**bable-sublime:**
![screen shot 2015-02-24 at 2 49 23 pm](https://cloud.githubusercontent.com/assets/4658558/6358888/723cb452-bc34-11e4-8683-e4d45d312ff9.png)

I'm using the [predawn](https://github.com/jamiewilson/predawn) theme. Any idea why this is happening?

**Comment by zertosh** [comment]
@aldendaniels It's the theme. https://github.com/jamiewilson/predawn/blob/4024b8/predawn.tmTheme#L164-L171

Predawn colors `variable` scopes, which `babel-sublime`/`JavaScriptNext` match. The "stock" JavaScript, which is what `sublime-react` is based on, does not match `variable` - which is why you see it with the default color. If you place your cursor over any text and press `shift+control+p`, Sublime will show you in the status bar what scope was matched. You can use this information to tweak the theme to your liking.

**Comment by zertosh** [comment]
Fun story @aldendaniels: I accidentally left predawn on after I tested it, and I noticed something interesting. The problem you're having might actually be a _good thing_, here is why: https://github.com/babel/babel-sublime/issues/50

**Comment by aldendaniels** [comment]
@zertosh - thanks for the explanation! The `shift+control+p` shortcut will also come in handly.
