### ISSUE TITLE
Names of static functions aren't scoped

### ISSUE THREAD

**Issue by Dashed** [babel/babel-sublime#54]
In the following:
```js
Deck.get = function get(keyPath) {
//...
};
```

`get` in `function get(keyPath)` isn't scoped to `entity.name.function.js` (and thus not colorized).

It's only scoped to `meta.function.static.js`.

**Comment by zertosh** [comment]
Fixed in https://github.com/babel/babel-sublime/pull/55. Should be in Package Control in ~30min.

**Before:**
![019ba98e-bfe9-11e4-8da4-de93d1c13c50](https://cloud.githubusercontent.com/assets/830952/6434294/905b3f76-c053-11e4-8461-5f00f3d7f178.png)

**After:**
![02ccbcee-bfe9-11e4-88e7-b52cc6145723](https://cloud.githubusercontent.com/assets/830952/6434296/94a64896-c053-11e4-8137-85948655cb5f.png)

**Comment by Dashed** [comment]
@zertosh Thanks! :+1:

**Comment by zertosh** [comment]
np <del>@ Arthur</del> @Dashed
