### ISSUE TITLE
Breaking Syntax

### ISSUE THREAD

**Issue by mattdesl** [babel/babel-sublime#60]
The following code loses all syntax highlighting after `{ //first comment`.

The issue looks to be because of `i<p` -- using spaces as in `i < p` fixes it.

```js
function foo() {
    let i = 0, p = 2, a = true, b = false;
    let next = i<p ? a : b;
    if (!next) { //first comment
        console.log("test")
    } else { //second comment
        console.log("test B")
    }
}
```

Apologies if this is the wrong repo for this ticket.

**Comment by zertosh** [comment]
Hey @mattdesl, this is the right repo. The problem is this one https://github.com/babel/babel-sublime/issues/29. Basically, it's where to draw line between what looks like a JSX tag vs a less-than comparison. The reason we can't 100% determine whether something is JSX is because Sublime can't do multiline matches - and a JSX tag can span multiple lines.

For this particular case, where the characters following the `<p` are spaces followed by a `?`, I can make a matching exception since it's a pretty common case. Right now, JSX tags are basically anything that starts with `<`, has some letters, then either a space or `>` or `/>`.

I'm a little tied up today, but I'll get the fix in this weekend.

**Comment by mattdesl** [comment]
Cool, thanks. 

I don't use JSX so I would also be open to some option or config to just have it disabled. :smile:

**Comment by zertosh** [comment]
@mattdesl The fix should be in Package Control within an hour.

Sadly you can't pick-and-choose like that :disappointed: But, if you're not at all interested in JSX or flow types (coming soon), then may I suggest you try https://github.com/Benvie/JavaScriptNext.tmLanguage. That's strictly modern JavaScript. In fact, it's the basis for ES6 support in `babel-sublime`.
