### ISSUE TITLE
Move snippets to separate plugin

### ISSUE THREAD

**Issue by roadhump** [babel/babel-sublime#71]
How about an idea to create separate ST plugin with snippets from `SNIPPETS.md`, something like `react-es6-snippets `? These snippets are useful and it is not fun to copy them by hands. I can do it by myself, just look for approval, hope there is no any scary legal stuff.

**Comment by zertosh** [comment]
Someone did that already (see https://github.com/babel/babel-sublime/issues/31#issuecomment-76528169). React snippets alone don't make sense under the Babel org, but having them included by default as part of `babel-sublime` has its own problems (see the earlier thread). An ES6 plus React snippets package would make sense, but I can't really maintain that because... I don't use snippets :expressionless:

**Comment by roadhump** [comment]
Great, sorry, should check issues before asking

**Comment by zertosh** [comment]
no problem. btw, great job on `SublimeLinter-eslint`!
