### ISSUE TITLE
syntax highlighting of HTML/XML snippets 

### ISSUE THREAD

**Issue by hiscodeness** [babel/babel-sublime#77]
I'd like to have syntax highlighting of multiline HTML and XML strings, as that is something that is available with the default JavaScript view. Here's the default view for JavaScript files:

![image](https://cloud.githubusercontent.com/assets/8625258/7039632/7d08f6c4-ddcd-11e4-80a9-aaf1cc26d08f.png)

And here's the same content with babel highlighting: 

![image](https://cloud.githubusercontent.com/assets/8625258/7039626/6eaa7f9e-ddcd-11e4-9eb4-bb6ba24a97e9.png)

Any thoughts on adding support for HTML/XML highlighting?

**Comment by zertosh** [comment]
@hiscodeness It's not that it's available in the stock JavaScript syntax definition, it's that it's incorrectly handling template strings. The stock definition doesn't recognize template strings at all, so it treats everything inside of one like regular js. That's why in your example it _appears_ as highlighted html, when in fact, it's highlighted js. Notice below how the `for` and `with` are highlighted.

![tdtsx](https://cloud.githubusercontent.com/assets/830952/7047713/4b8a19ca-dddc-11e4-952c-6097f957eb8c.png)

babel-sublime does the correct thing, which is to match the content of template strings as strings, and the content of `${..}` as expressions. Not all themes color this correctly though. For example, I like [dracula](https://github.com/zenorocha/dracula-theme), but it doesn't color method parens, so in substitutions they inherit the yellow of strings.

![kgvzf](https://cloud.githubusercontent.com/assets/830952/7047777/bd05b578-dddc-11e4-8a80-d21b207a1577.png)

**Comment by hiscodeness** [comment]
Ok, thanks for clearing that up for me and setting me straight. :-) Closing this as bogus request.
