### ISSUE TITLE
meta.group.braces.round.function.arguments

### ISSUE THREAD

**Issue by bathos** [babel/babel-sublime#86]
This scope applies correctly for bare function invocations and method invocations:

    foo();
    bar.foo();

But it's missing when the function is or appears to be a constructor, with or without new:

    Foobar();

Whose parens instead receive meta.group.braces.round.js meta.brace.round.js

**Comment by zertosh** [comment]
I see this with `new` but not when it's a bare invocation on a capitalized function:

```
foo()
   ^^---- meta.group.braces.round.function.arguments.js
   |_____ meta.group.braces.round.function.arguments.js

Foo()
   ^^---- meta.group.braces.round.function.arguments.js
   |_____ meta.group.braces.round.function.arguments.js

new Foo();
       ^^---- meta.brace.round.js
       |_____ meta.brace.round.js
```

**Comment by bathos** [comment]
Yup, you're right. Not sure why I thought it happened in the second case, too, it's just the third one.

**Comment by bathos** [comment]
Oh, wait, yes I do -- try this:

    Foo(arg)

**Comment by zertosh** [comment]
Oh I see what you mean. You've hit another issue like https://github.com/babel/babel-sublime/issues/85. The reason why the parens are matched differently for `()` and `(a)` is because of the same multi-line limitation. Since you can pass anything into a function (things that you'd write out across multiple lines), you have to match _open parens followed by anything that is not a close parens_ as meta.brace.round, which then recurses over the regexs again.

I know you're working on a theme and this must be very frustrating. Sometimes you can mask these syntax limitations by fudging with your colors a bit. Check out this [comment](https://github.com/babel/babel-sublime/issues/50#issuecomment-75886137).

**Comment by bathos** [comment]
Got it, makes sense. I have been grouping colors like you've suggested there when it helps with these things. Apologies for spamming issues; it's not really clear to me which are solvable bugs and which are just limitations of tmTheme, though I'm starting to get a feel for it.

**Comment by zertosh** [comment]
No worries - you're not spamming. I've tagged the ones that are fixable with "Bug". I'll get to them this weekend.
