### ISSUE TITLE
Scope for class names

### ISSUE THREAD

**Issue by bathos** [babel/babel-sublime#87]
Currently the following rules apply in most cases:

- A lowercase identifier is variable.other.readwrite
- An all-uppercase identifier is variable.other.constant

It seems reasonable also to recognize that variables which begin with a capital are constructors. The only time constructors become targettable is when they are being invoked to create an instance:

`new Foo()`: meta.instance.constructor entity.name.type.new

How about entity.name.class or entity.name.constructor? Even in class declarations, the name does not get a targettable scope currently.

**Comment by zertosh** [comment]
I'm confused on what it is exactly that you're asking for

**Comment by bathos** [comment]
Sorry. This one is indeed a feature request, not a bug. I mean to say that it would be awesome if 'MyConstructor' in the following examples received a common scope like 'entity.name.constructor':

    class MyConstructor {}

    new MyConstructor()

    MyConstructor

The second one already does get a targettable scope (entity.name.type.new) but the others don't. The last may be too opinionated, I don't know, but since the all-caps of MYCONSTANT is acknowledged as a naming convention that in itself is indicative of being a constant, it seems reasonable to me that this acknowledgement of naming conventions could be extended to MyConstructor (initial capital, followed by either all lowercase or mixed lowercase and uppercase).

**Comment by zertosh** [comment]
> `class MyConstructor {}`

In this case, `MyConstructor` gets `entity.name.class`, which I think makes sense, since you're defining a class, not instantiating a constructor.

>  `new MyConstructor()`

Here, `MyConstructor` gets `meta.instance.constructor`, which I also think makes sense, for the opposite reason as above. You might not have noticed this, but if you try `new ObjectBag.My.Constructor()`, the entire name is still `meta.instance.constructor` - the periods are ignored.

> `MyConstructor`

Heh yeah wayyy too opinionated. Consider that namespaces are often written with a capital too. Remember that the you can't get too specific with the naming because unlike syntax definitions (which are applied on a per-file basis), themes don't switch with file type. So, if your theme is too specific too one syntax, opening say an HTML file or Scala file, will look like crap.

Also, people have their opinions on self-instantiating constructor functions, but the fact is that ES6 classes can only be invoked with `new` as per the [spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ecmascript-function-objects-call-thisargument-argumentslist).

**Comment by bathos** [comment]
Well awesome, I somehow missed entity.name.class for the first case! That's the one I thought was more important, but I was mistaken that it was absent.

I totally agree re: use of new. I'm not sure why acknowledging the naming convention is "wayyy" too opinionated ("regular" opinionated would do I think) since it's an even more commonly agreed on convention than CAPCONSTANT, but I agree it wouldn't be possible to differentiate between actual classes and objects-as-namespaces that share this naming convention so I understand the reasoning.

**Comment by zertosh** [comment]
heh I'm kidding with the extra "yyy". Even the DOM API follows "CAPCONSTANT", so I'd call that a defacto standard :stuck_out_tongue:
