### ISSUE TITLE
Colour scheme seems to be inconsistent with screenshots

### ISSUE THREAD

**Issue by rbhalla** [babel/babel-sublime#97]
A small difference I can't really wrap my head around.

My object keys seem to be in yellow, and every dot is highlighted red. In the screenshots below I'm editing a .jsx file set to use the JavaScript(Babel) syntax in sublime.

![screen shot 2015-04-15 at 16 39 32](https://cloud.githubusercontent.com/assets/5897045/7162763/63975f34-e38e-11e4-9b14-8320bc168697.png)
![screen shot 2015-04-15 at 16 39 48](https://cloud.githubusercontent.com/assets/5897045/7162768/667b57fa-e38e-11e4-8e40-35a6d4e6cae0.png)

Currently I'm only using it for .jsx files (I haven't fully started using es6 syntax in my normal .js files) and am moving over from sublime-react. Ideally I'd like to retain the normal colour matching with jsx support. Am I able to revert back to the highlighting shown in the readme screenshots?

**Comment by zertosh** [comment]
So there is no "normal" color matching. Sublime syntax highlighting is composed of two parts: A syntax definition, and a theme that responds to the "scopes" in the definition with a certain color. babel-sublime is first and foremost the former, a syntax definition. We [bundle](https://github.com/babel/babel-sublime#setting-a-color-scheme) a Monokai-like theme, that understands a few more scopes that are relevant to JSX/ES6. You're free to pair up the babel-sublime syntax with whatever theme you like (I personally use [dracula](https://github.com/zenorocha/dracula-theme)).

For example, in the case of the "red dot", what you're seeing is whatever theme you have selected, responding to the correctly identified "keyword.operator.accessor" scope. If you're simply concerned about mismatch between "JavaScript (Babel)" and "JavaScript" files, you can set "JavaScript (Babel)" for all js types. That shouldn't affect your workflow since we're already supported by the major packages that depend on knowing the syntax name (mostly linters).

Hope this helps!

**Comment by rbhalla** [comment]
Hi zertosh,

Thanks for that great explanation. I think my main issue here is that those particular highlights only appear on files where I use Javascript(Babel) highlighting. I'm currently using Monokai(SL) which I believe is the default theme. Even when switching over the bundled Phoenix theme I still see these odd syntax highlights. So based on my limited understanding, it seems that this theme is adding those specific highlights.

I'm assuming from your response this isn't an intended affect caused by this extension, so I'm not sure what is actually causing it.

**Comment by zertosh** [comment]
Ah, I think I understand your question now. So the stock JavaScript syntax is actually pretty limited. Not just in terms of modern JS constructs like `class` and arrow functions, but also in terms of fine detail in existing constructs like the `.` when accessing a property. babel-sublime is more thorough and actually lets themes know that `.` is a thing, whereas before, those things went unmatched (and thus uncolored). Since themes are written to be general-use across different languages (think about how different CSS and JS are), they target agnostic constructs like "keyword.operator". That can mean different things in different languages, but ensures at least a somewhat consistent look across them. So that's why you're that every theme is coloring the dot when you have "JavaScript (Babel)" selected.

**Comment by rbhalla** [comment]
Ahh ok, in that case how would I achieve a colour as consistent as the screenshots if not by using the standard Monokai theme and the bundle Phoenix theme?

**Comment by zertosh** [comment]
The screenshots are using the bundled "Monokai Phoenix" so yeah that's one option. (Oceanic Next Theme)[https://github.com/voronianski/oceanic-next-theme] and [Predawn](https://github.com/jamiewilson/predawn) have pretty good support, but they look very different than Monokai.

**Comment by rbhalla** [comment]
That's the thing, the Phoenix thing doesn't seem to be an option as the same thing happens with it.

![screen shot 2015-04-16 at 16 19 35](https://cloud.githubusercontent.com/assets/5897045/7184302/7a575cc6-e454-11e4-80c7-b4d44e276731.png)

**Comment by zertosh** [comment]
oh no, I'm soooo sorry. My eyes deceived me. The screenshots are outdated :( The red dot is correct when using Monokai Phoenix. I'll get new ones out. Again, I'm sorry for dragging this convo on my mistake.

PS: Making perfectly aligned screenshots is really hard :stuck_out_tongue:. It took me half a day to make those 4. So I tend to not update them frequently.

**Comment by rbhalla** [comment]
Haha, no problem :)

I'll mark this issue as closed since it really isn't a problem then. If you find any themes that have the old theme behaviour and still look Monokai let me know!
